# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCEDocCore ] && mkdir -p DCEDocCore
          [ ! -d camera-enhancer-docs ] && git clone --depth 1 https://github.com/dynamsoft-docs/camera-enhancer-docs.git camera-enhancer-docs
          [ ! -d Docs-Template-Repo-Preview-DCV2 ] && git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cd camera-enhancer-docs && git pull && cd .. && cp -rfp ./camera-enhancer-docs/* ./DCEDocCore/
          cd Docs-Template-Repo-Preview-DCV2 && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DCEDocCore/
          cd DCEDocCore && bundle exec jekyll build --incremental
          python3 /home/ubuntu/ftp.py /home/ubuntu/DCEDocCore/_site/ ./www.dynamsoft.com/camera-enhancer/docs/core/ prod
  
  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCEDocCore-preview ] && mkdir -p DCEDocCore-preview
          [ ! -d camera-enhancer-docs-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/camera-enhancer-docs.git camera-enhancer-docs-preview
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cd camera-enhancer-docs-preview && git pull && cd .. && cp -rfp ./camera-enhancer-docs-preview/* ./DCEDocCore-preview/
          cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./DCEDocCore-preview/
          sed -i -e "1,3s/blob\/main$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCEDocCore-preview/_config.yml
          cd DCEDocCore-preview && bundle exec jekyll build --incremental && cd ..

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCEDocCore-preview/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/core/

          
