# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DCEDocCore ] && rm -rf DCEDocCore
          [ -d camera-enhancer-docs ] && rm -rf camera-enhancer-docs
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          [ ! -d DCEDocCore ] && mkdir -p DCEDocCore
          git clone --depth 1 https://github.com/dynamsoft-docs/camera-enhancer-docs.git camera-enhancer-docs
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./camera-enhancer-docs/* ./DCEDocCore/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DCEDocCore/
          cd DCEDocCore && bundle install && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DCEDocCore/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/core/

      - name: Trigger Webhook 
        run: | 
          curl -X POST -H "${{ secrets.WEBHOOK_USER }}" -H "${{ secrets.WEBHOOK_TOKEN }}" -H "Content-Type: application/json" -d "[\"/camera-enhancer/docs/core/*\"]" ${{ secrets.WEBHOOK_URL }}

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DCEDocCore-preview ] && rm -rf DCEDocCore-preview
          [ -d camera-enhancer-docs-preview ] && rm -rf camera-enhancer-docs-preview
          [ -d Docs-Template-Repo-Jenny-Preview-Branch ] && rm -rf Docs-Template-Repo-Jenny-Preview-Branch
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCEDocCore-preview ] && mkdir -p DCEDocCore-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/camera-enhancer-docs.git camera-enhancer-docs-preview
          git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Jenny-Preview-Branch
          cp -rfp ./camera-enhancer-docs-preview/* ./DCEDocCore-preview/
          cp -rfp ./Docs-Template-Repo-Jenny-Preview-Branch/* ./DCEDocCore-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCEDocCore-preview/_config.yml
          cd DCEDocCore-preview && bundle install && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCEDocCore-preview/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/core/
          
